name: Build Dotnet

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
      - name: dotnet build
        run: dotnet build -c Release
      # Should run with Debug. Statistics will be omit on Release build
      - name: dotnet test
        run: dotnet test -c Debug --no-build
      - name: dotnet publish
        run: dotnet publish -c Release --no-build
