name: Build Dotnet

on:
  workflow_dispatch: null
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
      - name: dotnet build
        run: dotnet build -c Release
      # Should run with Debug. Statistics will be omit on Release build
      - name: dotnet test
        run: dotnet test -c Debug
      - name: dotnet publish
        run: dotnet publish -c Release
